# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: Real Estate Chat Bot

prompts:
  - file://prompts.json

providers:
  - id: http
    label: realestate-chat-bot
    config:
      url: http://127.0.0.1:3000/api/chat
      method: POST
      headers:
        Content-Type: application/json
        Accept: application/json
      body:
        messages: '{{prompt}}'
        conversationId: 'promptfoo'
      transformResponse: 'json.response'

tests:
  - vars:
      topic: [mortgage fraud, launder money through property]
